### ISSUE TITLE
unable to connect on usb device (Not enough endpoints)

### ISSUE THREAD

**Issue by mp-007** [jacklinquan/usbserial4a#3]
Hi,

I tried to run your exemple.py file but I have this following error on Android 9 (tablet model Samsung tab A SM-T510):

Traceback (most recent call last):
   File "/storage/emulated/0/***/example.py", line 29, in <module>
     1)      # Number of stop bits(1, 1.5 or 2)
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/usbserial4a/serial4a.py", line 54, in get_serial_port
     return CdcAcmSerial(device_name, *args, **kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/usbserial4a/cdcacmserial4a.py", line 56, in __init__
     super(CdcAcmSerial, self).__init__(*args, **kwargs)
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/serial/serialutil.py", line 240, in __init__
     self.open()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/usbserial4a/cdcacmserial4a.py", line 82, in open
     self._open_single_interface()
   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.7/site-packages/usbserial4a/cdcacmserial4a.py", line 112, in _open_single_interface
     raise SerialException(msg)
serial.serialutil.SerialException: Not enough endpoints - need 3, got 2 

I'm using a otg samsung connector GH98-40216A. I also tried via your pyusbtool (on google play) but I have the same error.

Can you help on this?

**Comment by jacklinquan** [comment]
Hi Marcets,
Thank you for the report.
Can you tell me what usb-to-serial device did you connect it to?
The samsung connector GH98-40216A is only the "usb on the go" adaptor, there is a device connected on the other side of it. This device must be a usb-to-serial device.
Based on the traceback info, the vendor id and product id of this device is not automatically recognized. So it decided to use the general CDC ACM driver to try to connect to it.
This package only works for "usb-to-serial device", not all usb devices. For example, it won't connect to a usb flash disk.

**Comment by mp-007** [comment]
Hi,

thanks you for your quick answer. I'm using an usb flash disk, so it's is the reason why it's not working.
